### ISSUE TITLE
Define the API Interface

### ISSUE THREAD

**Issue by jpcamara** [OpenWorksGroup/openbadges-directory#1]
Need to define what the API will look like and what endpoint(s) will be exposed. To start, openbadges-discovery will be the only consumer so it will be a driver of the first stab at this.

Assuming some kind of single search endpoint to start, in that endpoint:
- What will the request interface be? 
  - Searchable by all data in the badge class?  
  - How will those pieces be sent? How advanced will the search characteristics be?
- What will the the response look like?

**Comment by jpcamara** [comment]
To be clear, this isn't suggesting anything crazy like using XML or defining some sort of RPC interface. Moreso does the search do something like "search?tags=tag1,tag2,tag3", and does the response come back as a json array of badge objects. 

For the request interface, I'm open to a ?q= type of approach as one of the options, for simple global searches. But I think more granular pieces will be necessary so you can do things like specifically search on a tag, or by an issuer.

For the response, a simple array of objects could work. But additional metadata may be desirable. Adding a metadata layer would allow for things like pagination information to be returned.

**Comment by stenington** [comment]
@jpcamara I'm happy with `search?tags=tag1,tag2,tag3` style search, I think. I guess the response could be a json object with a `data` key (or `results` or `badges` or something) so additional metadata could be added to that object, like pagination info.

As for what should be searchable, I'm going to pick through @chloeatplay's UX wireframes next week to make sure all the development work is captured, and in that process I think I'll have a more definitive list of what kinds of things we'll let users ask about and search for.

**Comment by stenington** [comment]
@jpcamara So it looks like we'll need to
- get badges by "recency"
- get badges by tag
- search

For "recency" I think if we record the first date the directory sees a particular badge class and sort by that, that would be sufficient. I understand with dummy data that might all be the same date for now, and I think that's fine.

I'm not sure how sophisticated the search should be. Part of the answer probably comes from what's easy given the backend, and also maybe from user testing. Certainly to start something like keyword search using name and description would be sufficient.

We also have a filter on the discovery side that essentially just says "get badges", which is a bit funny. I suppose I could just issue an empty search or something, or you could expose an endpoint that just lists all badges sorted by id, maybe?

**Comment by stenington** [comment]
Actually I think we also need to be able to retrieve a single badge by id as well.

**Comment by jpcamara** [comment]
I've added in what I think will satisfy discoveries needs.

/search endpoint - allows general search by a "q" param. Allows tag search by a comma separated "tags" param. They can be used in conjunction as well to filter down things further.

/recent endpoint - hands back the most recent badges in descending order by index timestamp.

A couple thoughts:
- Does /recent suffice for the "get badges" concept?
- Should the directory have a /recent endpoint? I _think_ it's ok. Just want your input
- Should the /search endpoint allow no-arg searches? I'm thinking not, particularly if there is a different endpoint to just get everything back generally. 
- When you say retrieve a badge by id - what will be the use case? I haven't added in the badge url yet (as the id), but I will be doing that shortly. In the meantime though, are you specifically looking into the directory by id? 

In addition to the endpoints, you can paginate and limit the results. It's in the docs, but basically the combination of "page" and "limit" allow you to get more results.

**Comment by stenington** [comment]
/recent is probably fine as a "get badges" endpoint. I think I was getting confused by the example filters on the wireframe, but of course it would make sense to have a way to get back to that view when viewing badges filtered in some other way, which wasn't occurring to me because of reasons.

What's the concern with a /recent endpoint? I don't see a problem with it, but that doesn't mean there isn't one.

I agree that we don't need no-arg searches.

The badge-by-id use case is something like:
- user browses badges through discovery app
- user sees a badge they want and clicks on it
- user sees badge detail page
- user bookmarks page
- user later clicks bookmark

Up until the bookmarking, I don't care about the id really. But if/when they want to jump straight back to that badge detail page, I need to be able to ask the directory for a specific badge and really only care in that moment about that one badge. So that was my thinking... being able to ask for badge by id seemed like the simplest solution off hand.

**Comment by jpcamara** [comment]
Yea I don't think I have a real concern with /recent. I think there was a part of me that thought it strange to have such a specific endpoint for a search service - but why not?

I'll remove the no arg searches. 

The badge-by-id need is interesting. I think it's def fair to put that into the directory, but it's a little mind-bending to think about how all this stuff fits together sometimes.
For instance - at what point in Pathways does a badge get stored in the system? Does it ever? If someone were to bookmark a badge, should it just be stored at that point with the data already returned by the search? Either way, a refresh capability would be important, though technically at that point you'd know the original location of the badge and could refresh directly from that? The issuer would be the one with the freshest data, the directory could be in the process of reindexing and not have gotten to it yet and missed an update or something. Though realistically, I imagine badges shouldn't be changing very often unless there was a mistake, right?

It's the decentralization that raises interesting questions. There's one place that stores the original, freshest badge class, but people want to be able to easily use it in other places. Things!

On a different note - think I could get a sample of the badges that will be used in pathways? Is that something you folks have available right now?

**Comment by threeqube** [comment]
> think I could get a sample of the badges that will be used in pathways? Is that something you folks have available right now?

I believe we are working on a sampling but don't have them yet. What kind of placeholder data can you use in the mean time? cc/ @chloeatplay

**Comment by jpcamara** [comment]
I am currently using sample badges to test out the API, just wanted to make sure I wasn't missing anything for what Pathways will need. Just keep me posted when some samples are available so I can try them out, thanks!

**Comment by stenington** [comment]
Yeah, I wasn't sure if the discovery app would essentially "cache" badges in its own DB or just rely on the directory for badge data at all times. I understand the latter probably wouldn't scale well if the directory become heavily relied on, but then at least there'd be an incentive for caching in the client app: speed. For a prototype it seemed easier to me to let the directory manage badges and the discovery app manage pathways, but I also don't want to then build a bunch of stuff in the wrong place and have to fix it later. 

The refresh issue is tricky... I'd **really** like to ignore it and say that until the spec talks about how to publish changes to a badge class, changing it is considered illegal and so we don't have to deal with it. However, I assume in the real world it's gonna happen. But... I dunno. I think we can start by assuming the data won't be changing and then actually do a little exploration to see how often it does once we have a real directory running with real badges in it.

**Comment by kayaelle** [comment]
Been thinking about the publish changes to a badge class. This is tricky for everyone issuing badges and the directory thinking adds even more complexity. I think this is an argument for bringing back versioning into badge classes. We used to have version in the old spec. At the time I didn't clearly understand how to use it. 

There's really no way to prevent changing the badge class. There's been some discussion of baking the badge class into the badges. That would atleast timestamp the badge data. If the badge class was baked into a badge as well as contain a version - that could inform the directory and save some work. Granted - issuers may not always update their versions but I think a directory would give them incentive to do so. (maybe).

**Comment by threeqube** [comment]
This is a really great point @kayaelle. I've also created this ticket in the discussion repo: https://github.com/mozilla/openbadges-discussion/issues/12
