### ISSUE TITLE
Should we have an export for the directory?

### ISSUE THREAD

**Issue by jpcamara** [OpenWorksGroup/openbadges-directory#10]
Since this will be an open service, should we expose an ability to dump the entire contents of the directory? That way people can take the data and do what they want with it. 
It probably makes sense, since we want this to be open and available generally. NPM let's you do it (https://www.npmjs.org/doc/registry.html#Can-I-run-my-own-private-registry)

Not super important right away, but something to keep in mind. Hence, this issue.

**Comment by threeqube** [comment]
:+1:
