### ISSUE TITLE
Send Email When an Endpoint Gets Registered

### ISSUE THREAD

**Issue by kayaelle** [OpenWorksGroup/openbadges-directory#40]
It would be good to be notified when an issuer registers an endpoint so that we can review the indexing. For now will send to kerri@achievery.com but may change that to a broader group (maybe the working group?) so that more support is in the loop.

**Comment by threeqube** [comment]
Hmmm, not sure the working group email is the right one. Might be a separate dedicated mailing list?

**Comment by kayaelle** [comment]
Agreed. That'd be much better @threeqube. directory-support@ ?

**Comment by threeqube** [comment]
Yeah something like that. Should we create one now or later?

**Comment by kayaelle** [comment]
Now would be great. Probably don't need everyone on it - kerri & jp for now? Maybe you if you want?

**Comment by threeqube** [comment]
kk, Will set it up. Ok for it to be a @badgealliance email?

**Comment by kayaelle** [comment]
Yep. Thanks!

**Comment by threeqube** [comment]
:+1:
